#! /bin/sh

###################
## configuration ##
###################

## workspace name
## font needed wuncon-siji
bspc monitor -d '' '' '' '' '' '' '' ''

## common bspwm configuration
bspc config border_width        1
bspc config window_gap         	5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config top_padding 18


## color settings
bspc config focused_border_color "#b7b7b7" 
bspc config normal_border_color "#232831"


##################
## window rules ##
##################

## workspace 1 (labs)
bspc rule -a st desktop='^1' follow=on focus=on

## workspace 2 (web browsers)
bspc rule -a Firefox-esr desktop='^2' follow=on focus=on

## workspace 3 (text-editors)
bspc rule -a Geany desktop='^3' follow=on focus=on
bspc rule -a Code desktop='^3' folloe=on focus=on

## workspace 4 (office)
bspc rule -a Wps desktop='^4' follow=on focus=on
bspc rule -a Et desktop='^4' follow=on focus=on
bspc rule -a Wpp desktop='^4' follow=on focus=on

## workspace 5 (multimedia)
bspc rule -a Audacity desktop='^5' follow=on focus=on
bspc rule -a mpv desktop='^5' follow=on focus=on
bspc rule -a soundconverter desktop='^5' follow=on focus=on
bspc rule -a Gnome-mpv desktop='^5' follow=on focus=on
bspc rule -a Xfburn desktop='^5' follow=on focus=on

## workspace 6 (graphic-editors)
bspc rule -a Evince desktop='^6' follow=on focus=on
bspc rule -a Gimp desktop='^6' follow=on focus=on
bspc rule -a Gimp-2.8 desktop='^6' follow=on focus=on
bspc rule -a Inkscape desktop='^6' follow=on focus=on

## workspace 7 (file-manager)
bspc rule -a Pcmanfm desktop='^7' follow=on focus=on

## workspace 8 (system-settings)
bspc rule -a Lxappearance desktop='^8' state=floating follow=on
bspc rule -a Nitrogen desktop='^8' follow=on focus=on
bspc rule -a Xfce4-settings-manager desktop='^8' state=floating follow=on
bspc rule -a Lightdm-gtk-greeter-settings desktop='^8' state=floating follow=on
bspc rule -a System-config-printer.py desktop='^8' state=floating follow=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a Pavucontrol desktop='^8' state=floating follow=on
bspc rule -a Lxrandr desktop='^8' state=floating follow=on
bspc rule -a Arandr desktop='^8' state=floating follow=on

## need to be floating
bspc rule -a Audacious state=floating follow=on
bspc rule -a Viewnior state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Gpicview state=floating follow=on
bspc rule -a URxvt state=floating follow=on


###############
## autostart ##
###############

# Load bitmap fonts
xset fp+ ~/.fonts/misc &

## reload compton
pkill compton
compton -b &

# system tray
pkill xfce4-power-manager
xfce4-power-manager &

# network applet
nm-applet &

# clipboard manager
pkill clipit
clipit &

# volume icon
pkill volumeicon
volumeicon &

# keybind daemon
pkill sxhkd
sxhkd &

## reload the xsettingsd, a minimal x settings daemon
pkill xsettingsd
xsettingsd &

## set the wallpaper
feh --bg-fill /usr/share/lubuntu/wallpapers/wallhaven-nature.png

## load dunst
pkill dunst
dunst &

## reload the cursor theme
xsetroot -cursor_name left_ptr

## or polybar?
pkill polybar
polybar -c ~/.config/bspwm/polybar top &
